AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
  TargetRubyVersion: 2.3

Layout/EndOfLine:
  EnforcedStyle: lf

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
